[package]
name = "sourcepan"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[dependencies]
git2 = "0.7"
chrono = "0.4.4"
preferences = "1.1.0"
notify = "4.0.3"
glib = "0.5.0"

[dependencies.gtk]
version = "0.4.1"
features = ["v3_22"]

